title: Dylan Nguyen # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  Cloud Developer @Basware, Finland | Data Engineer @Trafore Oy, Finland | Master of Security and Cloud Computing (Security) @Aalto University
  <br><br>
  <a href="https://xkcd.com/1838/">ML in a nutshell</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/dylan-nguyen-43014190/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
